spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DHKIM92_POSTGRES_DATABASE_URL:jdbc:postgresql://localhost:5432/blog_local}
    username: ${DHKIM92_POSTGRES_USERNAME:blog_admin}
    password: ${DHKIM92_POSTGRES_PASSWORD:blog_admin}
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    username: ${DHKIM92_POSTGRES_USERNAME:blog_admin}
    password: ${DHKIM92_POSTGRES_PASSWORD:blog_admin}
    baseline-on-migrate: true

jwt:
  issuer: "https://www.dohoon-kim.kr"
  audience: "https://www.dohoon-kim.kr"
  access-token:
    secret: ${DHKIM92_JWT_ACCESS_TOKEN_SECRET:access_token_secret_key}
    expiration: 900000 # 15 minutes
  refresh-token:
    secret: ${DHKIM92_JWT_REFRESH_TOKEN_SECRET:refresh_token_secret_key}
    expiration: 1209600000 # 14 days

server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

logging:
  level:
    root: ${DHKIM92_BLOG_LOGGING_LEVEL:DEBUG}
    org.flywaydb: INFO
    org.hibernate: INFO
