spring:
  cache:
    type: redis
  redis:
    host: ${DHKIM92_REDIS_HOST:127.0.0.1}
    port: ${DHKIM92_REDIS_PORT:6379}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DHKIM92_POSTGRES_HOST}:${DHKIM92_POSTGRES_PORT}/${DHKIM92_POSTGRES_DB_NAME}
    username: ${DHKIM92_POSTGRES_USERNAME:blog_admin}
    password: ${DHKIM92_POSTGRES_PASSWORD:blog_admin}
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    username: ${DHKIM92_FLYWAY_USERNAME:blog_admin}
    password: ${DHKIM92_FLYWAY_PASSWORD:blog_admin}
    baseline-on-migrate: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${DHKIM92_OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${DHKIM92_OAUTH2_GITHUB_CLIENT_SECRET}
            scope: profile
            redirect-uri: ${DHKIM92_OAUTH2_GITHUB_CALLBACK_URL:http://localhost:3000/sign-in/oauth2/callback}
            authorization-grant-type: authorization_code

jwt:
  issuer: "https://www.dohoon-kim.kr"
  audience: "https://www.dohoon-kim.kr"
  access-token:
    secret: ${DHKIM92_JWT_ACCESS_TOKEN_SECRET:access_token_secret_key}
    expiration: 900000 # 15 minutes
  refresh-token:
    secret: ${DHKIM92_JWT_REFRESH_TOKEN_SECRET:refresh_token_secret_key}
    expiration: 1209600000 # 14 days

server:
  port: 8080
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
  media:
    host: ${DHKIM92_MEDIA_HOST:http://localhost:8080}
    path: ${DHKIM92_MEDIA_PATH:/Users/terrapin/.volumes/media}

cors:
  frontend: ${DHKIM92_CORS_FRONTEND_URL:http://localhost:3000}
  host: ${DHKIM92_CORS_HOST:http://localhost:3000}

logging:
  level:
    root: ${DHKIM92_LOGGING_LEVEL:DEBUG}
    org.flywaydb: ERROR
    org.hibernate: ERROR
    org.apache: ERROR
    com.zaxxer.hikari: ERROR
