ALTER TABLE IF EXISTS member
    ADD COLUMN IF NOT EXISTS is_blocked BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE IF EXISTS member
    DROP COLUMN IF EXISTS is_activated;

ALTER TABLE IF EXISTS oauth2_member
    DROP COLUMN IF EXISTS access_token;