CREATE TABLE IF NOT EXISTS refresh_token (
    id uuid PRIMARY KEY,
    member_id uuid NOT NULL,
    token VARCHAR(512) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expire_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT refresh_token_fk_member FOREIGN KEY(member_id) REFERENCES member(id)
            ON DELETE CASCADE
);